apiVersion: v1
kind: Service
metadata:
  name: config-server-service
spec:
  selector:
    app: config-server
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30080
  type: NodePort