apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-registry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camera-registry
  template:
    metadata:
      labels:
        app: camera-registry
    spec:
      containers:
        - name: camera-registry-server
          image: endienasg/foxstudios-factory-camera-registry:main
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: config-registry-database-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: config-registry-database-secret
                  key: POSTGRES_PASSWORD
