apiVersion: v1
kind: Service
metadata:
  name: camera-registry-service
spec:
  selector:
    app: camera-registry
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30081
  type: NodePort